---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: no-config
spec:
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: with-config
  annotations:
    'insights.fairwinds.com/app-groups': 'all-resources'
spec:
  type: service
